<?php
/**
 * @see Mageist_Sanalpos_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<?php /*
<div class="sanalpos-top-notice">
    <h4><?php echo Mage::helper('sanalpos')->__('Mageist Sanalpos Extra Help')?></h4>

    <?php

    $externalContent = file_get_contents('http://checkip.dyndns.com/');
	preg_match('/Current IP Address: ([\[\]:.[0-9a-fA-F]+)</', $externalContent, $m);
	$externalIp = $m[1];

    ?>

    <h5><?php echo Mage::helper('sanalpos')->__("Your server's outer ip address : ") . $externalIp; ?></h5>

</div>

*/ ?>