<div class="top_cart">
    <?php $_cartQty = intval($this->getSummaryCount()) ?>
    <?php if($_cartQty): ?>
        <a class="cart_not_empty clearfix" href="<?php echo $this->getUrl('checkout/cart')?>">
            <span><?php echo $_cartQty; ?></span>
        </a>
    <?php else: ?>
        <span class="cart_empty clearfix">
            <span><?php echo $_cartQty; ?></span>
        </span>
    <?php endif ?>
</div>