<?php if(Mage::getStoreConfig('testimonial/general_option/enable_sidebar') == 1):?>
	<?php $latestTestimonial = $this->getTestimonialsLast()?>
	<?php if(count($latestTestimonial) > 0):?>
	<div class="block block-testimonial-sidebar">
		<div class="block-title">
			<strong><span><?php echo $this->__('Latest Testimonial')?></span></strong>
		</div>
		<div class="block-content">
			<?php foreach($latestTestimonial as $_item):?>
				<div class="testimonial-sidebar-content clearer">
					<div class="std">
						   <?php
                                $count = $this->getNumberWordsOnSidebar();
								$_description = $_item->getTestimonial();
								$short_desc = $this->getContentTestimonialSidebar($_description, $count);
								echo $short_desc;
						   ?>
						<a href="<?php echo $this->getUrl('testimonial')?>#<?php echo $_item->getName();?>" title=""><br/><?php echo $this->__("View more")?></a>
					</div>
					<div class="name-date-testimonial">
						<h6 class="name"><?php echo $_item->getName();?></h6>
						<h6 class="date"><?php 
							$date = new Zend_Date($_item->getCreatedTime(), null, Mage::app()->getLocale()->getLocaleCode());
							echo $date->get(Zend_Date::DATE_LONG);
						?></h6>
					</div>
				</div>
			<?php endforeach;?>
		</div>
	</div>
	<?php endif ?>
<?php endif ?>