<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Avail
 * @version    1.2.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div id = "aw_avail_stock_wrapper">
    <?php if (!$this->getProduct()->getId()): ?>
        <div>
            <?php echo $this->__('Stock status is unknown'); ?>          
        </div>
        <?php return; ?>
    <?php endif; ?>

    <?php $_label = $this->parseVars($this->getAppliedStockLabel()); ?>

    <?php if ((int) $this->getAppliedRule()->getType() !== AW_Avail_Model_Rules::IMAGE_ONLY): ?>   
        <div>
            <?php echo $_label['text']; ?>
        </div>
        <?php if ((int) $this->getAppliedRule()->getType() === AW_Avail_Model_Rules::TEXT_ONLY): ?>
        </div>
        <?php return; ?> 
    <?php endif; ?>
<?php endif; ?>

<?php if (!empty($_label['image'])): ?>
    <div>
        <img src ="<?php echo Mage::helper('avail')->getImgUrl($_label['image']);?>" class = "aw_avail_stock_label"
             alt = "<?php echo $this->htmlEscape($_label['text']); ?>" title = "<?php echo $this->htmlEscape($_label['text']); ?>"
             />
    </div>
<?php endif; ?>
</div>